### ISSUE TITLE
Titan-forged PvP Trinkets

### ISSUE THREAD

**Issue by Bellzubab** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#174] opened 2017-03-16 16:30 UTC
You added the "Platinum Disks of ___" trinkets, but not the "Titan-forged Rune of ___" trinkets with the 3.1 update.

http://wotlk.openwow.com/?search=titan-forged+rune

http://wowwiki.wikia.com/wiki/Titan-Forged_Rune_of_Determination

Patch 3.1.0 (14-Apr-2009): Added.

And so on, for the others listed in that openwow link.

They should both be added, or neither (depending on how you look at it with regards to the PvP season).

**Comment by Bellzubab** [comment] 2017-03-16 16:47
Also, http://wowwiki.wikia.com/wiki/Titan-Forged_Cord_of_Dominance is purchasable, but http://wowwiki.wikia.com/wiki/Titan-Forged_Cord_of_Salvation isn't... (at least I couldn't see it on my priest/mage).

**Comment by madsoigard** [comment] 2017-03-16 17:05
Lots of other items as well with the Ulduar patch.

**Comment by lajhar** [comment] 2017-03-17 17:47
For some reason with the new patch the WG vendors (Knight Dameron - **32294** and Stone Guard Mukar - **32296**) went fool, and few level 213 appeared, while level 200 Titan-Forged gear disappeared.
Level 200 items should be readded, and level 213 items should be removed until we start arena season 6.

**Removable items:**
46088 - Platinum Disk of Swiftness
46087 - Platinum Disk of Sorcery 
46086 - Platinum Disk of Battle
46079 - Titan-Forged Cord of Dominance
46063 - Titan-Forged Leather Chest of Salvation

**Items to readd:**
44895 - Titan-Forged Greaves of Salvation
44894 - Titan-Forged Greaves of Triumph
44896 - Titan-Forged Sabatons of Dominance
44897 - Titan-Forged Sabatons of Salvation
44898 - Titan-Forged Sabatons of Triumph
44893 - Titan-Forged Boots of Triumph
44892 - Titan-Forged Boots of Salvation
44891 - Titan-Forged Boots of Dominance
44899 - Titan-Forged Slippers of Dominance
44900 - Titan-Forged Slippers of Salvation
44902 - Titan-Forged Plate Helm of Triumph
44901 - Titan-Forged Plate Headcover of Salvation
44903 - Titan-Forged Chain Helm of Triumph
44904 - Titan-Forged Mail Helm of Dominance
44905 - Titan-Forged Ringmail Helm of Salvation
44908 - Titan-Forged Leather Helm of Triumph
44906 - Titan-Forged Leather Helm of Salvation
44907 - Titan-Forged Leather Helm of Dominance
44910 - Titan-Forged Hood of Dominance
44909 - Titan-Forged Hood of Salvation

**Comment by Bellzubab** [comment] 2017-03-17 17:50
The 200 items have been gone for a while, not just since the patch yesterday.

Players can only see the gear that they can equip, so there's 213 cloth/leather/mail/plate stuff to be removed (if that's the direction they decide to take).

Edit: Or I meant the stuff their class is eligible for.

**Comment by madsoigard** [comment] 2017-03-17 17:52
How soon will you be able to add them?

**Comment by lajhar** [comment] 2017-03-17 17:52
"The 200 items have been gone for a while, not just since the patch yesterday."

Whatever, they should be there.

"Players can only see the gear that they can equip, so there's 213 cloth/leather/mail/plate stuff to be removed (if that's the direction they decide to take)."

I checked in GM mode (GMs can see every item in the vendor) and only those 2 items are available in the vendor. Kinda weird.

**Comment by Bellzubab** [comment] 2017-03-17 17:54
Is your GM character a rogue/druid? But yeah, weird.

From my mage (15 seconds before I post this): http://puu.sh/uNjHH/4790181748.jpg

**Comment by madsoigard** [comment] 2017-03-27 15:38
Bum(his)p. Should be an easy fix.

Also when does the arena season change and where can we get information on these things? There are no forums beside interface, classes and professions.

**Comment by lajhar** [comment] 2017-03-29 19:24
Fixed.
Fix confirmed on PTR.

**Closed as completed** 2017-03-30 15:18 UTC
Labels: [Dev.OnLive], [Fix.Confirmed]
