### ISSUE TITLE
The Oculus - Drakes Not Spawning after defeat of Drakos The Interrogator

### ISSUE THREAD

**Issue by lxHACKDxl** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#12] opened 2017-01-20 15:35 UTC
http://www.wowhead.com/npc=27654/drakos-the-interrogator#comments

By Syphris (828 – 3·12) on 2008/12/08 (Patch 3.0.3)
		
This boss if easy for everyone but the healer. Tank him in the center. Avoid the orbs once they stop as they will exlode shortly after. He also casts Magic Pull which brings all players up to him. Run back to a safe location after this as he will spawn several orbs after pulling your group to him. The tank will occasionally be tossed into the air by Thundering Stomp bit it is nothing to worry about. Keep dancing the dance and he'll be dead in no time.

**After this boss dies 3 NPC will be freed from the cages on the same platfrom as Drakos.** The one on the left will give you a Emerald Drake. The one on the right will give the Amber Drake. The center NPC gives the Ruby Drake. The Emerald Drake is your healer later on, the Amber is your DPS, and the Ruby is your tank. I suggest 1 Ruby, and 2 each of the others.

The highlighted bold statement does not happen.

Tested twice on 1/20/2017

**Comment by Zerixx** [comment] 2017-01-20 22:53
This should be working as intended. We're gonna try to replicate.

**Comment by Zerixx** [comment] 2017-01-20 22:55
@lajhar

**Comment by Zerixx** [comment] 2017-01-20 23:19
After this was tested, he couldn't replicate. Closing.

**Closed as completed by Zerixx** 2017-01-20 23:19 UTC
Labels: [Core.Instance], [Core.PvE], [Dev.WorkingAsIntended], [Dev.Report.Confirmed], [Priority.High]
