### ISSUE TITLE
[Quest] Convocation at Zol'Heb

### ISSUE THREAD

**Issue by phreaque** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#148] opened 2017-03-08 11:55 UTC
The quest "Convocation at Zol'Heb" at Zul'Drak is not working
http://www.wowhead.com/quest=12730/convocation-at-zolheb

Using the provided quest item "Prophet of Akali Convocation" will just result in an error "You can't do that yet"
http://www.wowhead.com/item=39566/prophet-of-akali-convocation

**Comment by dangreenberggit** [comment] 2017-04-28 16:34
Duplicate of #102

**Closed as completed** 2017-05-06 17:39 UTC
