### ISSUE TITLE
Buffing people in combat does not give combat (ft. big picture proof)

### ISSUE THREAD

**Issue by madsoigard** [FeenixServerProject/Wrath_3.3.5_Issue_tracker#74] opened 2017-02-10 00:23 UTC
![ayy combat bug](https://cloud.githubusercontent.com/assets/25508888/22808984/79cbcfc0-ef2f-11e6-894b-6c5e4fecaa95.jpg)

**Comment by lajhar** [comment] 2017-02-10 11:57
This picture shows someone entered combat just now, while you have buffed him about 3-5 sec ago. In addition, you still haven't casted Flash Heal on him.

You should have taken the picture 0,1 sec later, and you could see that you enter combat as intended. If you buff someone not in combat, then he enters combat, shouldn't make you enter combat aswell, only if you cast buffs on him while he is in combat.

You can create another pointless issues, or you can open a proper one with suffcient proof if you still believe it's an issue.

**Comment by eladvmago** [comment] 2017-02-10 12:56
sorry to disappoint, I took picture only 1.41sec later (after 2 finished flash heals)
![wowscrnshot_020917_233444](https://cloud.githubusercontent.com/assets/25687283/22827485/73d3e4ea-ef98-11e6-9647-72785290e925.jpg) now, may I ask for a proof that it does put you in combat? (obviously in pvp)
Edit: sometimes it actually works, guess I will test it more in skirmish later

**Comment by lajhar** [comment] 2017-02-10 20:56
I got this video, did this test today on prelive:

http://sendvid.com/flu21cve

Sorry for the bad quality, 3 windows + recording is something my PC cannot handle properly.
Didn't encounter the issue you have posted, whatever I did.

**Comment by madsoigard** [comment] 2017-02-10 22:27
https://www.youtube.com/watch?v=cpzba161zjE

It might work differently with different spells, but we should be getting in combat from any buff.

**Comment by Zerixx** [comment] 2017-02-12 16:40
Looks fixed on PreLive.

**Closed as completed** 2017-02-13 16:41 UTC
Labels: [Dev.OnPreLive], [Dev.OnLive], [Core.Misc], [Fix.Confirmed]

**Comment by madsoigard** [comment] 2017-02-23 20:24
Hey, when will this be applied to live?
